### ISSUE TITLE
Booking search request

### ISSUE THREAD

**Issue by fbvarelam** [fbvarelam/hotel-bookings#2]
The **BookingSearchRequest** class generated by openApi doc generator should be inmutable but it's not. I tried adding properties to the maven plugin and coding programatically but it didn't work.
It's  also necessary to take into account that this class has Jakarta validations, not provided by openapi.

**src/main/java/org/plexus/hotelbookings/infrastructure/rest/model/BookingSearchRequest.java**

**Comment by juanfjb** [comment]
Se puede aplicar la inmutabilidad modificando las plantillas de generación, pero eso realmente va a ser matar moscas a cañonazos. Yo optaría por la sencillez y declararía el contrato sin api first, me apoyaria en anotaciones para mostrarlo mediante Swagger, aunque mostrar conocimientos de ello también es un plus. Si quieres obvia este punto de mejora
